version: '3'
services:
  db:
    image: mysql:latest
    environment:
      - MYSQL_DATABASE=lamp-db
      - MYSQL_USER=lamp-user
      - MYSQL_PASSWORD=mypassword
      - MYSQL_ROOT_PASSWORD=rootpassword
    networks:
      - lamp-docker
    volumes:
      - "./:/docker-entrypoint-initdb.d"
  www:
    depends_on:
      - db
    build: .
    volumes:
      - "./:/var/www/html"
    ports:
      - 8083:80
      - 443:443
    networks:
      - lamp-docker
  phpmyadmin:
    depends_on:
      - db 
    image: phpmyadmin/phpmyadmin
    ports:
      - 8001:80
    environment:
      - PHA_HOST=db
      - PHA_PORT=3306
    networks:
      - lamp-docker
networks:
  lamp-docker:
    driver: bridge